bot-token:
server-id:
icon-storage:
  use: true
status-updater:
  use: false
broadcaster:
  use: false
  channels: []
simple-forwarder:
  use: false
  channels: []
translator-forwarder:
  use: false
  channels: []
  languages:
    - en_US
    - ko_KR
channel-forwarder:
  use: false
  prefix: '#'
  channels:
    - discordChannelId shortName
  default-listening-channels:
    - shortName
  default-speaking-channels:
    - shortName
group-linker:
  use: false
  groups:
    - discord minecraft